name: Build Windows EXE and attach to Release

on:
  push:
    tags: ["v*"]        # auto-builds on new tags like v1.0.1
  workflow_dispatch:     # lets you build for an existing tag (e.g. v1.0.0)
    inputs:
      tag:
        description: "Tag to build (e.g. v1.0.0)"
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt pip install -r requirements.txt
          pip install "pyinstaller>=6.6" "pyinstaller-hooks-contrib>=2024.8"

      - name: Build exe with PyInstaller
        run: pyinstaller --noconfirm --onefile --windowed --name ecodices_marcxml_downloader app.py

      - name: Package artifact
        run: powershell Compress-Archive -Path dist\* -DestinationPath ecodices_marcxml_downloader-win64.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ecodices_marcxml_downloader-win64
          path: ecodices_marcxml_downloader-win64.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ecodices_marcxml_downloader-win64

      - name: Publish/Update Release for the tag
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}
          files: ecodices_marcxml_downloader-win64.zip
